name: Ansible Lint
description: Run Ansible Lint
author: Ansible by Red Hat <info@ansible.com>

inputs: 
  args:
    description: |
      Arguments to be passed to the ansible-lint
      Options:
        "-p"
    required: true
  targets:
    description: |
      "./playbooks"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.args }}
  env:
    TARGETS: ${{ inputs.targets }}