name: Ansible Lint  # feel free to pick your own name

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone
    - uses: actions/checkout@v1

    - name: echo
    - run: echo "hello world"