name: Ansible Lint  # feel free to pick your own name

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v1
    - name: Lint Ansible Playbook

    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0.post0

            
           
