name: Ansible Lint  # feel free to pick your own name

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
      - name: Git clone our repository
        uses: actions/checkout@v1

      - name: Build Docker image
        run: docker build -t xkeyops/ansible-lint .

      - name: Save Docker image layer cache
        run: |
            docker save -o /caches/ansible-lint.tar xkeyops/ansible-lint

      - name: Load Docker image layer cache
        run: |
            set +o pipefail
            docker load -i /caches/ansible-lint.tar | true

      - name: Build ansible-lint Docker image
        run: docker build --cache-from=ansible-lint -t xkeyops/ansible-lint ./

      - name: Run ansible-lint (test)
        run: sh ./script.sh

      - name: Save Docker image layer cache
        run: |
            mkdir -p /caches
            docker save -o /caches/ansible-lint.tar xkeyops/ansible-lint