name: CI-cloud-infra  # feel free to pick your own name

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v1

    - name: echo
      run: ls -lah

    - name: docker build registry
      run: |
        docker login docker.pkg.github.com --username xKeyOPS

    - name: docker ps
      run: docker images