name: Ansible Lint  # feel free to pick your own name

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
      - name: Git clone our repository
        uses: actions/checkout@v1

      - name: Build Docker image
        run: docker build -t ansible-lint .

      - name: Save Docker image layer cache
        run: |
            docker save -o ansible-lint.tar ansible-lint

      - name: Run ansible-lint (test)
        run: sh ./script.sh

