name: Ansible Lint  # feel free to pick your own name

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v1
    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
    -  uses: ansible/ansible-lint-action@master
    -  with:
        targets: "playbooks"
        args: "-p"
