name: CI-cloud-infra  # feel free to pick your own name

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      uses: actions/checkout@v1

    - name: echo
      run: ls -lah

    - name: docker build
      run: docker build -t local.cloud.registry:5000/develop/ed:my-docker-dind

    - name: docker ps
      run: docker images 