name: Ansible Lint  # feel free to pick your own name

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v1
      name: Lint Ansible Playbook

    - name: Load Docker image layer cache
      run: |
            set +o pipefail
            docker load -i /caches/ansible-lint.tar | true
    - name: Build ansible-lint Docker image
      run: docker build --cache-from=ansible-lint -t xkeyops/ansible-lint ./

    - name: Run ansible-lint (test)
      run: sh ./script.sh
